presentation  = """Je suis passioner de developement et plus géneralement\
    d'informatique. J'apprend exclusivement au auto-didacte. Pour le moment\
    je fait exclusivement des projet personne personne ou je me donne aucune\
    limite. J'essait un maximum de chose de façon a savoir se qui me plait\
    vraiment et dans le but d'en apprendre toujours plus sur le monde\
    merveilleur de l'informatique. En ayant toucher a beaucoup de domaine de\
    l'informatique (haut niveau comme bas niveau) je suis en capaciter de\
    m'addapter très rapidement."""



[[skills]]
name = "C++"
img = "img/skills/cpp.png"
infos = """Je suis fort en c++ numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\
         optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis\
         obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam\
         nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,\
         tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\
         quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos\
         sapiente officiis modi at sunt excepturi expedita sint? Sed quibusda"""


[[skills]]
name = "C++"
img = "img/skills/cpp.png"
infos = """Je suis fort en c++ numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\
         optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis\
         obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam\
         nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,\
         tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\
         quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos\
         sapiente officiis modi at sunt excepturi expedita sint? Sed quibusda"""



[[skills]]
name = "C++"
img = "img/skills/cpp.png"
infos = """Je suis fort en c++ numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\
         optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis\
         obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam\
         nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,\
         tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\
         quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos\
         sapiente officiis modi at sunt excepturi expedita sint? Sed quibusda"""
