presentation  = """Je suis passioner de developement et plus géneralement\
    d'informatique. J'apprend exclusivement au auto-didacte. Pour le moment\
    je fait exclusivement des projet personne personne ou je me donne aucune\
    limite. J'essait un maximum de chose de façon a savoir se qui me plait\
    vraiment et dans le but d'en apprendre toujours plus sur le monde\
    merveilleur de l'informatique. En ayant toucher a beaucoup de domaine de\
    l'informatique (haut niveau comme bas niveau) je suis en capaciter de\
    m'addapter très rapidement."""



[[skillsGroup]]
name = "Général"
color = "green"
    [[skillsGroup.skill]]
    name = "Algorithmie"
    note = 0.9
    comment = "Ma capaciter a comprendre et construire des algorithme fonctinelle"
    [[skillsGroup.skill]]
    name = "Math"
    note = 0.8

[[skillsGroup]]
name = "Language de programation"
color = "blue"
    [[skillsGroup.skill]]
    name = "C"
    note = 0.6
    [[skillsGroup.skill]]
    name = "C++"
    note = 0.55
    [[skillsGroup.skill]]
    name = "C#"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Java"
    note = 0.8
    [[skillsGroup.skill]]
    name = "Dart"
    note = 0.8
    [[skillsGroup.skill]]
    name = "JS"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Python"
    note = 0.9


[[skillsGroup]]
name = "Frame work"
color = "red"
    [[skillsGroup.skill]]
    name = "Unity"
    note = 0.7
    [[skillsGroup.skill]]
    name = "Nodejs"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Hugo"
    note = 0.85
[[skillsGroup]]
name = "Frame work"
    [[skillsGroup.skill]]
    name = "Unity"
    note = 0.7
    [[skillsGroup.skill]]
    name = "Nodejs"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Hugo"
    note = 0.85
[[skillsGroup]]
name = "Frame work"
color = "red"
    [[skillsGroup.skill]]
    name = "Unity"
    note = 0.7
    [[skillsGroup.skill]]
    name = "Nodejs"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Hugo"
    note = 0.85
