name = "Ulysse"
birthDate = 2005-05-06
localisation = "Poitiers"
phone = "01.02.03.04.05"
email = "somemail@mailbox.com"
profilPick = "img/profil.jpeg"
homeHeaderBackground = "img/home_header_background.png"
fileCV = "cv.pdf"

homeProjects = ["better-bus", "bacterio", "raycaster-c", "connect-4"]
cvProjects = ["better-bus", "raycaster-c"]


[[socials]]
name = "Github"
icon = "fa-brands fa-github"
link = "https://github.com/Bubulleux"

[[socials]]
name = "Twitter"
icon = "fa-brands fa-twitter"
link = "https://twitter.com"
