heroSubTitle = [
    "Je m’appelle Ulysse aka Bubulle.",
    "Je suis développeur autodidacte et passionner.",
]

presentation  = """ Je suis développeur autodidacte pour le moment. Je suis
grandement passionné par tout ce qui touche a l’informatique de prêt ou de
loin. Je ne me donne aucune limite et j’essaie de toucher a un maximum de
domaine de l’informatique pour trouver ce qu’il me plait vraiment. Je peux
utiliser python pour créer rapidement un petit outil, je peux utiliser des
langages bas niveau comme C ou C++ pour créer des algorithmes complexe qui
demande beaucoup de performance. Ou je peux utiliser du C#, Java ou Dart pour
créer des applications ou des jeux. Je ne reste pas bloquer dans ma zone de
confort et j’essais toujours d'en apprendre plus sur les différents algorithme,
technologie et méthode de développement qui existe."""


hobbies = ["Programmation et développement", "Jeux vidéo", "Apprendre de nouvelle chose"]

shortSkills = [
    "Apprendre de nouveaux language",
    "Comprendre des problème",
    "Rationel",
]

[[language]]
name = "Français"
note = 0.9
level = "Natif"

[[language]]
name = "Anglais"
note = 0.7
level = "B2"

[[study]]
name = "Lycée bac géneralement a Nelson Mandela Poitiers"
description = """Bac géneralement avec Mathématiques, Numérique Science Informatique 
et Options Math éxpèret."""
from = "2023"
weight = 1
[[study]]
name = "Licence d’informatique a l'universiter de Poitiers"
description = "CMI Informatique"
from = "2024"
to = "2026"
weight = 2

[[professionalExperience]]
name = "Création d’un application modile en auto didacte"
description = "Veiller consulter mon site web pour plus d’information"
from = "2021"
to = "2023"
weight = 1



[[skillsGroup]]
name = "Général"
description = """Je suis très passioner par tout se qui touche au science et 
particulièrement les Math. Mais si mon niveau n’est pas vraiment technique
je comprend et connais beaucoup de chose particulièrement en Physique. Mon 
expèrience a écrire tout type de programe me donne un bon niveau en Algorithmie
"""
color = "green"
    [[skillsGroup.skill]]
    name = "Algorithmie"
    note = 0.9
    comment = "Ma capaciter a comprendre et construire des algorithme fonctinelle"
    [[skillsGroup.skill]]
    name = "Math"
    note = 0.8

[[skillsGroup]]
name = "Language de programation"
description = """Comme dit plus tôt je suis une personne assez curieuse quand
il en vient a parler de sujet qui touche l’informatique. Cela ma permit 
de toucher a plein de language de programation. Cette experience dans tout 
c’est language me permet d'en apprendre encore de nouveaux avec grand faciliter.
"""
color = "blue"
    [[skillsGroup.skill]]
    name = "C"
    note = 0.6
    [[skillsGroup.skill]]
    name = "C++"
    note = 0.55
    [[skillsGroup.skill]]
    name = "C#"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Java"
    note = 0.8
    [[skillsGroup.skill]]
    name = "Dart"
    note = 0.8
    [[skillsGroup.skill]]
    name = "JS"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Python"
    note = 0.9


[[skillsGroup]]
name = "Frame work"
color = "red"
    [[skillsGroup.skill]]
    name = "Unity"
    note = 0.7
    [[skillsGroup.skill]]
    name = "Nodejs"
    note = 0.6
    [[skillsGroup.skill]]
    name = "Hugo"
    note = 0.85

[[skillsGroup]]
name = "Outil"
description = """Pour programer j’utilise essentielement des programe open-source
et si possible qui ne sont pas possider par une grand companie. Même si j’ai 
aussi la capaciter de m’adapter et d'utiliser certain outil comme VS code et 
la Suite Jetbrain. Je code habituelement sous Arch linux avec NeoVim et je
met tout monde code sur Github."""
    [[skillsGroup.skill]]
    name = "Linux"
    note = 0.7

    [[skillsGroup.skill]]
    name = "Windows"
    note = 0.9

    [[skillsGroup.skill]]
    name = "NeoVim"
    note = 0.8

    [[skillsGroup.skill]]
    name = "Visual Studio Code"
    note = 0.9

    [[skillsGroup.skill]]
    name = "Suit Jeibrain"
    note = 0.8

    [[skillsGroup.skill]]
    name = "Git"
    note = 0.85

    [[skillsGroup.skill]]
    name = "Libre Office"
    note = 0.95

